# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: CopyFiles@2
  displayName: 'Copy files to: $(Build.ArtifactStagingDirectory)/Templates'
  inputs:
    SourceFolder: deployment
    Contents: '*.json'
    OverWrite: true
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Templates'

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install --production'
    
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'

#- task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'
#
#- script: |
#    npm install
#    npm run build
#  displayName: 'npm install and build'
